version: '3'
services:
  spring-app:
    image: myapp
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Service-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
